# Generated by Django 5.0.4 on 2024-06-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accountmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone'),
        ),
    ]
