# Generated by Django 5.0.4 on 2024-05-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('comment', models.TextField()),
                ('profession', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Comment',
                'verbose_name_plural': 'User Comments',
            },
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.RenameField(
            model_name='contactmodel',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='contactmodel',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
