# Generated by Django 5.0.4 on 2024-05-22 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
    ]
