# Generated by Django 5.0.4 on 2024-05-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogmodel_short_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='catigories',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='short_info',
            field=models.TextField(),
        ),
    ]
