# Generated by Django 5.0.4 on 2024-05-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='discount',
        ),
    ]
