# Generated by Django 5.0.4 on 2024-05-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productmodel_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='discount_price',
            new_name='discount',
        ),
    ]
